### ISSUE TITLE
DNA Lab Patch Freezes the Game

### ISSUE THREAD

**Issue by xion-g-chee** [acemon33/dw2-tt#1]
After applying the DNA Lab Patch, the game freezes after pressing "New Game". Tested with it being the only patch and everything set to default. Tested with mod and unmodded versions of the game. 

Edit: After further testing, changing the values on boss stats causes a bad sector error. Forgot to mention that I'm playing this game on RetroArch.

Edit 2: Downloaded ECCRegen and applied it and the bad sector issue went away. Also, applying all the patches and using ECCRegen right after seems to fix any errors that may have been causing them to not work correctly. The mod seems to be working now. I've tested the Digi-Line patch which does allow me to properly set the amount of digimon I want.

**Comment by acemon33** [comment]
I appreciate your contribution. I will mention it in the next release.
