### ISSUE TITLE
Server Items don't seem to be correct

### ISSUE THREAD

**Issue by AVellucci** [acemon33/dw2-tt#2]
I know the config files set the items for the app.
But it looks like the items for DW2 Alternative are incorrect
I know there's a config file but unfortunately I'm not sure howI would evengo about finding the coresponding values for the items to correct it myself.
A fix or someone pointing me asto where to look to fix it myself wouldbe amazing.

**Comment by acemon33** [comment]
Thanks for mentioning that, the fix will be available in the next release.

**Comment by acemon33** [comment]
If you want to get info about items, the data is located in
/AAA/4.AAA/DATAFILE/WAZADATA and /AAA/4.AAA/DATAFILE/ITEMDATA within the game bin.

**Comment by acemon33** [comment]
The addresses were extracted from the DW2 CheatEngine file using a Python script,
but it seems there are some incorrect values.
